openai_api_key="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"

OPENAI_API_KEY="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"

BARD_API_KEY="eQgrkaLkZrpY7I5LkFfbyWxPPtGazvKK3mJ8A4RG62mVqO7TjWXyJ2SKN2jxtbVoXV2Txg."